// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_QuickUltraLiteStudioLayers)
QT_DECLARE_EXTERN_RESOURCE(qmake_QtQuickUltralite_Layers)
QT_DECLARE_EXTERN_RESOURCE(QuickUltraLiteStudioLayers_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(QuickUltraLiteStudioLayers_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_QtQuickUltralite_Layers)

class QtQuickUltralite_LayersPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickUltralite_LayersPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_QtQuickUltralite_Layers)
QT_KEEP_RESOURCE(qmlcache_QuickUltraLiteStudioLayers)
QT_KEEP_RESOURCE(qmake_QtQuickUltralite_Layers)
QT_KEEP_RESOURCE(QuickUltraLiteStudioLayers_raw_qml_0)
QT_KEEP_RESOURCE(QuickUltraLiteStudioLayers_raw_qml_0_extra_qmldirs)
    }
};



#include "QuickUltraLiteStudioLayersplugin_QtQuickUltralite_LayersPlugin.moc"
