// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_UntitledProjecthhhh)
QT_DECLARE_EXTERN_RESOURCE(qmake_UntitledProjecthhhh)
QT_DECLARE_EXTERN_RESOURCE(UntitledProjecthhhh_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_UntitledProjecthhhh)

class UntitledProjecthhhhPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    UntitledProjecthhhhPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_UntitledProjecthhhh)
QT_KEEP_RESOURCE(qmlcache_UntitledProjecthhhh)
QT_KEEP_RESOURCE(qmake_UntitledProjecthhhh)
QT_KEEP_RESOURCE(UntitledProjecthhhh_raw_qml_0)
    }
};



#include "UntitledProjecthhhhplugin_UntitledProjecthhhhPlugin.moc"
