// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_QuickUltraLiteStudioProfiling)
QT_DECLARE_EXTERN_RESOURCE(qmake_QtQuickUltralite_Profiling)
QT_DECLARE_EXTERN_RESOURCE(QuickUltraLiteStudioProfiling_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_QtQuickUltralite_Profiling)

class QtQuickUltralite_ProfilingPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickUltralite_ProfilingPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_QtQuickUltralite_Profiling)
QT_KEEP_RESOURCE(qmlcache_QuickUltraLiteStudioProfiling)
QT_KEEP_RESOURCE(qmake_QtQuickUltralite_Profiling)
QT_KEEP_RESOURCE(QuickUltraLiteStudioProfiling_raw_qml_0)
    }
};



#include "QuickUltraLiteStudioProfilingplugin_QtQuickUltralite_ProfilingPlugin.moc"
