// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_UntitledProjecthhhhContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_UntitledProjecthhhhContent)
QT_DECLARE_EXTERN_RESOURCE(UntitledProjecthhhhContent_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(UntitledProjecthhhhContent_raw_res_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_UntitledProjecthhhhContent)

class UntitledProjecthhhhContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    UntitledProjecthhhhContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_UntitledProjecthhhhContent)
QT_KEEP_RESOURCE(qmlcache_UntitledProjecthhhhContent)
QT_KEEP_RESOURCE(qmake_UntitledProjecthhhhContent)
QT_KEEP_RESOURCE(UntitledProjecthhhhContent_raw_qml_0)
QT_KEEP_RESOURCE(UntitledProjecthhhhContent_raw_res_0)
    }
};



#include "UntitledProjecthhhhContentplugin_UntitledProjecthhhhContentPlugin.moc"
