// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_QuickStudioDesignEffects)
QT_DECLARE_EXTERN_RESOURCE(qmake_QtQuick_Studio_DesignEffects)
QT_DECLARE_EXTERN_RESOURCE(QuickStudioDesignEffects_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_QtQuick_Studio_DesignEffects)

class QtQuick_Studio_DesignEffectsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_Studio_DesignEffectsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_QtQuick_Studio_DesignEffects)
QT_KEEP_RESOURCE(qmlcache_QuickStudioDesignEffects)
QT_KEEP_RESOURCE(qmake_QtQuick_Studio_DesignEffects)
QT_KEEP_RESOURCE(QuickStudioDesignEffects_raw_qml_0)
    }
};



#include "QuickStudioDesignEffectsplugin_QtQuick_Studio_DesignEffectsPlugin.moc"
